site_name: The Funding Cooperative DAO
copyright: <a href="https://twitter.com/FundingDao">Funding Cooperative DAO</a>
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences

plugins:
  - search:
